/** @type {import('tailwindcss').Config} */
// Force reload
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#17171c',
        ink: '#212121',
        'deep-green': '#003c33',
        'dark-navy': '#071829',
        canvas: '#ffffff',
        'soft-stone': '#eeece7',
        'pale-green': '#edfce9',
        'pale-blue': '#f1f5ff',
        hairline: '#d9d9dd',
        'border-light': '#e5e7eb',
        'card-border': '#f2f2f2',
        muted: '#93939f',
        slate: '#75758a',
        'body-muted': '#616161',
        'action-blue': '#1863dc',
        'focus-blue': '#4c6ee6',
        coral: '#ff7759',
        'coral-soft': '#ffad9b',
        'form-focus': '#9b60aa',
        error: '#b30000',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        success: '#059669',
        warning: '#d97706',
        /* Missing aliases for Recruiter pages */
        'brand-black': '#17171c',
        'brand-green': '#003c33',
        'canvas-stone': '#eeece7',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'Arial', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'hero': ['96px', { lineHeight: '1', letterSpacing: '-1.92px', fontWeight: '400' }],
        'product': ['72px', { lineHeight: '1', letterSpacing: '-1.44px', fontWeight: '400' }],
        'section-display': ['60px', { lineHeight: '1', letterSpacing: '-1.2px', fontWeight: '400' }],
        'section-heading': ['48px', { lineHeight: '1.2', letterSpacing: '-0.48px', fontWeight: '400' }],
        'card-heading': ['32px', { lineHeight: '1.2', letterSpacing: '-0.32px', fontWeight: '400' }],
        'feature-heading': ['24px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '400' }],
        'body-large': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'btn': ['14px', { lineHeight: '1.71', letterSpacing: '0', fontWeight: '500' }],
        'caption': ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'mono-label': ['14px', { lineHeight: '1.4', letterSpacing: '0.28px', fontWeight: '400' }],
        'micro': ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        /* Missing aliases for Recruiter pages */
        'display': ['60px', { lineHeight: '1', letterSpacing: '-1.2px', fontWeight: '400' }],
        'title': ['32px', { lineHeight: '1.2', letterSpacing: '-0.32px', fontWeight: '400' }],
        'subtitle': ['24px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '22px',
        'xl': '30px',
        'pill': '32px',
        'full': '9999px',
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
        'section': '5rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-down': 'slideDown 0.25s ease-out',
        'scale-in': 'scaleIn 0.25s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.97)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
